apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dispatcher-evaluator
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dispatcher.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-evaluator
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-evaluator
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-db
          image: {{ printf "%s:%s" .Values.postgres.image.repository .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ printf "%s-postgres" .Release.Name }}
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dispatcher.secretName" . }}
                  key: postgres-username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dispatcher.secretName" . }}
                  key: postgres-password
            - name: DB_NAME
              value: {{ include "dispatcher.dbName" . }}
          command:
            - sh
            - -c
            - |
              until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER"; do
                echo "Waiting for postgres..."
                sleep 1
              done
              # Wait until the table 'job_offers' exists (until migrations are applied)
              until psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c "\dt" | grep job_offers; do
                echo "Waiting for dispatcher database to be ready..."
                sleep 1
              done
      containers:
        - name: dispatcher-evaluator
          image: "{{ .Values.dispatcher.evaluator.image.repository }}:{{ .Values.dispatcher.evaluator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dispatcher.evaluator.image.pullPolicy }}
          env:
            {{- include "dispatcher.env" . | nindent 12 }}
            - name: RECRUITAIR_EVALUATOR_API_BASE_URL
              value: "http://{{ .Release.Name }}-evaluator-api:{{ .Values.evaluator.service.port }}"
            - name: RECRUITAIR_EVALUATOR_API_BEARER_TOKEN
              value: "supersecrettoken" # TODO: Change to use secret
              # valueFrom:
              #   secretKeyRef:
              #     name: {{ .Release.Name }}-evaluator-secret
              #     key: evaluator-api-bearer-token