{{- if .Values.dispatcher.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dispatcher-api
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "alb" }}
    # AWS ALB Annotations
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: recruitair-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- else }}
    # Nginx (Local) Annotations
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - http:
      paths:
      {{- $prefix := .Values.dispatcher.api.ingress.prefix | default "/api" }}
      - path: {{ if eq .Values.ingress.className "alb" }}{{ printf "%s*" $prefix }}{{ else }}{{ printf "%s(/|$)(.*)" $prefix }}{{ end }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-dispatcher-api
            port:
              number: {{ .Values.dispatcher.api.service.port }}
{{- end }}