apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dispatcher-api
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.dispatcher.api.service.type }}
  ports:
    - port: {{ .Values.dispatcher.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-api
    {{- include "..selectorLabels" . | nindent 4 }}
