kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: recruitair-dev
  region: eu-north-1
nodeGroups:
  - name: linux-nodes
    instanceType: t3.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    labels:
      ingress-ready: "true"