apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-extractor-api
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-extractor-api
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-extractor-api
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: extractor-api
          image: "{{ .Values.extractor.api.image.repository }}:{{ .Values.extractor.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.extractor.api.image.pullPolicy }}
          env:
            - name: MLFLOW_TRACKING_URI
              value: {{ .Values.mlflow.trackingUri }}
            - name: RECRUITAIR_PROMPT
              value: {{ .Values.extractor.api.prompt.name }}
            - name: RECRUITAIR_PROMPT_VERSION
              value: {{ .Values.extractor.api.prompt.version | quote }}
            - name: RECRUITAIR_MODEL
              value: {{ .Values.extractor.api.model.name }}
            - name: RECRUITAIR_MODEL_VERSION
              value: {{ .Values.extractor.api.model.version | quote }}
            - name: RECRUITAIR_OLLAMA_BASE_URL
              value: http://{{ .Release.Name }}-extractor-ollama:{{ .Values.extractor.ollama.service.port }}
          ports:
            - name: http
              containerPort: {{ .Values.extractor.api.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.extractor.api.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.extractor.api.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10