{{- if .Values.extractor.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-extractor-api
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    { { - if eq .Values.ingress.className "alb" } }
    # AWS ALB Annotations
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: recruitair-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    { { - else } }
    # Nginx (Local) Annotations
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    { { - end } }
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      {{- $prefix := .Values.extractor.api.ingress.prefix | default "/api" }}
      - path: {{ if eq .Values.ingress.className "alb" }}{{ printf "%s*" $prefix }}{{ else }}{{ printf "%s(/|$)(.*)" $prefix }}{{ end }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-extractor-api
            port:
              number: {{ .Values.extractor.api.service.port }}
  {{- if .Values.extractor.api.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.extractor.api.ingress.host }}
    secretName: {{ .Values.extractor.api.ingress.tls.secretName }}
  {{- end }}
{{- end }}