{{- if .Values.extractor.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-extractor-api
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.extractor.api.ingress.host }}
    http:
      paths:
      - path: {{ printf "%s(/|$)(.*)" (.Values.extractor.api.ingress.prefix | default "/api") }} 
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-extractor-api
            port:
              number: {{ .Values.extractor.api.service.port }}
  {{- if .Values.extractor.api.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.extractor.api.ingress.host }}
    secretName: {{ .Values.extractor.api.ingress.tls.secretName }}
  {{- end }}
{{- end }}