apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dispatcher-evaluator
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dispatcher.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-evaluator
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-evaluator
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: dispatcher-evaluator
          image: "{{ .Values.dispatcher.evaluator.image.repository }}:{{ .Values.dispatcher.evaluator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dispatcher.evaluator.image.pullPolicy }}
          env:
            {{- include "dispatcher.env" . | nindent 12 }}
            - name: RECRUITAIR_EVALUATOR_API_BASE_URL
              value: "http://{{ .Release.Name }}-evaluator:{{ .Values.evaluator.service.port }}"
            - name: RECRUITAIR_EVALUATOR_API_BEARER_TOKEN
              value: "supersecrettoken" # TODO: Change to use secret
              # valueFrom:
              #   secretKeyRef:
              #     name: {{ .Release.Name }}-evaluator-secret
              #     key: evaluator-api-bearer-token