apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-prometheus-pvc
  labels:
    app.kubernetes.io/name: prometheus
    {{- include "..labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ default "10Gi" .Values.prometheus.persistence.size }}
  storageClassName: {{ .Values.prometheus.persistence.storageClass }}