apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dispatcher-api
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-api
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-dispatcher-api
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: dispatcher-api
          image: "{{ .Values.dispatcher.api.image.repository }}:{{ .Values.dispatcher.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dispatcher.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.dispatcher.api.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.dispatcher.api.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.dispatcher.api.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10