apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-grafana
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-grafana
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          volumeMounts:
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-provisioning-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-dashboards
              mountPath: /opt/grafana-dashboards
              readOnly: true
          env:
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafana.adminCredentialsSecretName }}
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grafana.adminCredentialsSecretName }}
                  key: admin-password
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /grafana/
              port: {{ .Values.grafana.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /grafana/
              port: {{ .Values.grafana.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10

      volumes:
        - name: grafana-provisioning-dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-provisioning-dashboards-config
        - name: grafana-provisioning-datasources
          configMap:
            name: {{ .Release.Name }}-grafana-provisioning-datasources-config
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-grafana-pvc
        - name: grafana-dashboards
          configMap:
            name: {{ .Release.Name }}-grafana-dashboards-config