{{- if .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.grafana.ingress.host }}
    http:
      paths:
      - path: {{ printf "%s(/|$)(.*)" (.Values.grafana.ingress.prefix | default "") }} 
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-grafana
            port:
              number: {{ .Values.grafana.service.port }}
  {{- if .Values.grafana.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.grafana.ingress.host }}
    secretName: {{ .Values.grafana.ingress.tls.secretName }}
  {{- end }}
{{- end }}