# Configmap for the prometheus server (prometheus.yml)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-provisioning-datasources-config
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/grafana/provisioning/datasources/*.yaml").AsConfig | nindent 2 }}