apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-extractor-ollama
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-extractor-ollama
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-extractor-ollama
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ollama
          image: "{{ .Values.extractor.ollama.image.repository }}:{{ .Values.extractor.ollama.image.tag }}"
          imagePullPolicy: {{ .Values.extractor.ollama.image.pullPolicy }}
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          ports:
            - name: http
              containerPort: {{ .Values.extractor.ollama.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.extractor.ollama.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.extractor.ollama.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-extractor-ollama-pvc
