apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-postgres" .Release.Name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    {{- include "..selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      name: postgres
