apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-evaluator-api
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-evaluator-api
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-evaluator-api
        {{- include "..labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: evaluator-api
          image: "{{ .Values.evaluator.image.repository }}:{{ .Values.evaluator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.evaluator.image.pullPolicy }}
          env:
            - name: MLFLOW_TRACKING_URI
              value: {{ .Values.mlflow.trackingUri }}
            - name: RECRUITAIR_MODEL
              value: {{ .Values.evaluator.model.name }}
            - name: RECRUITAIR_MODEL_VERSION
              value: {{ .Values.evaluator.model.version | quote }}
          {{- if .Values.evaluator.awsSecret }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.evaluator.awsSecret }}
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.evaluator.awsSecret }}
                  key: aws-secret-access-key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.evaluator.awsSecret }}
                  key: aws-region
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.evaluator.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.evaluator.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.evaluator.service.port }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10