{{- if .Values.evaluator.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-evaluator-api
  labels:
    {{- include "..labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "alb" }}
    # AWS ALB Annotations
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: recruitair-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- else }}
    # Nginx (Local) Annotations
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.evaluator.ingress.host }}
    http:
      paths:
      - path: {{ printf "%s(/|$)(.*)" (.Values.evaluator.ingress.prefix | default "/api") }} 
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-evaluator-api
            port:
              number: {{ .Values.evaluator.service.port }}
{{- end }}